### ISSUE TITLE
server Not render the expected page 

### ISSUE THREAD

**Issue by orlowang** [lukeed/preact-cli-ssr#1]
Hi, it looks like server just render home page, then route to the page which user real visit to by JavaScript in browser. Expectation is the server render the page visit to by user, some help?

``` js
let url = req.url;
let body = render(h(App, { url }));
```
here, ```body```can't get the correct page structure to which the ```url``` points, it's designed like this or **Preact** bug ?

**Comment by lukeed** [comment]
Hey, 

I'm not sure why, but it's actually a behavior specific to the `now.sh` deployment. If you run this locally, you'll see that each route's is rendered from the server:

![viewsource](https://user-images.githubusercontent.com/5855893/34364870-fc4b35f2-ea3e-11e7-8711-75519a956ded.jpg)

I can chat with the ZEIT guys to try & get more insight, but the setup, as is, works correctly. I'm using it for a couple production sites 😄

**Comment by orlowang** [comment]
Thanks for the reply, and it's really a stupid mistake that I made that I changed the ```id``` of root div, but forget to change the server side.
``` js
// here the id not changed as app.js
const RGX = /<div id="app"[^>]*>.*?(?=<script)/i;
```
now it works.

**Comment by lukeed** [comment]
Oops, haha. Happens to all of us 😆
