### ISSUE TITLE
Flickering on first load

### ISSUE THREAD

**Issue by ghost** [lukeed/preact-cli-ssr#3]
Hi, @lukeed, once any of the routes are rendered for the first time the content would flicker, especially on smaller networks.

![webp net-gifmaker](https://user-images.githubusercontent.com/36133496/36230025-5f472d2e-11ee-11e8-8832-9ae8c2598186.gif)

Is there any way to fix this issue?

**Comment by lukeed** [comment]
Hey~! This is about to be fixed with https://github.com/developit/preact-cli/pull/489

It'll be available in the next minor release of the CLI -- probably tomorrow or Friday!
