### ISSUE TITLE
How to SSR the <head> dynamically?

### ISSUE THREAD

**Issue by johhansantana** [lukeed/preact-cli-ssr#4]
Hello, is there a way to handle the `<head></head>` tag dynamically(title, description, meta, etc)? Or even just set it up the first load time.

**Comment by lukeed** [comment]
Hey, yes! That's what the `prerender-urls.json` file is for. You can pass whatever you want, but by default the CLI handles title and description for you. Anything else you pass in will require that you add a custom template, which can then be attached via `--template [path]`. 

Docs for all this is (mostly) on the CLI's readme, but feel free to ask me any other questions if you need help!

**Comment by johhansantana** [comment]
I see. What about if you want to fetch some blog post and want the blog post title to be the actual page title? How do you go about setting that?

Using the `prerender-urls.json` file I can only hardcode the titles. If I set them via [preact-head](https://github.com/matthewmueller/preact-head) for example, and check the source code of the loaded page, it will still have the hardcoded title in the `prerender-urls.json` or if I set none there, it will get `<title>Preact CLI SSR</title>` instead.

Is this possible?

**Comment by lukeed** [comment]
Prerendering isn't meant for dynamic content. You will need to prerender a _shell_ of what you want & then update the dynamic parts during your server response.

Checkout my full answer here to the same question: https://github.com/developit/preact-cli/issues/488#issuecomment-364031214

**Comment by johhansantana** [comment]
Awesome! thank you @lukeed
